local addonName, addonTable = ...
local L = addonTable.L

local maps = {
	-- Eastern Kingdoms
	[L["ARATHI HIGHLANDS"]] 				= 14,
	[L["BADLANDS"]] 						= 15,
	[L["BLASTED LANDS"]]  					= 17,
	[L["BURNING STEPPES"]]  				= 36,
	[L["DUN MOROGH"]]  						= 27,
	[L["DUSKWOOD"]] 						= 47,
	[L["EASTERN PLAGUELANDS"]]  			= 23,
	[L["ELWYNN FOREST"]] 					= 37,
	[L["EVERSONG WOODS"]] 					= 94,
	[L["GHOSTLANDS"]] 						= 95,
	[L["HILLSBRAD FOOTHILLS"]] 				= 25,
	[L["LOCH MODAN"]] 						= 48,
	[L["NORTHERN STRANGLETHORN"]] 			= 50,
	[L["REDRIDGE MOUNTAINS"]] 				= 49,
	[L["SEARING GORGE"]] 					= 32,
	[L["SILVERPINE FOREST"]] 				= 21,
	[L["THE CAPE OF STRANGLETHORN"]] 		= 210,
	[L["TIRISFAL GLADES"]] 					= 18,
	[L["WESTERN PLAGUELANDS"]] 				= 22,
	[L["WESTFALL"]] 						= 52,
	[L["WETLANDS"]] 						= 56,
	-- Kalimdor
	[L["ASHENVALE"]]						= 63,
	[L["AZSHARA"]]							= 76,
	[L["DARKSHORE"]]						= 62,
	[L["DESOLACE"]]							= 66,
	[L["DUROTAR"]]							= 1,
	[L["DUSTWALLOW MARSH"]]					= 70,
	[L["FELWOOD"]]							= 77,
	[L["FERALAS"]]							= 69,
	[L["MULGORE"]]							= 7,
	[L["NORTHERN BARRENS"]]					= 10,
	[L["SOUTHERN BARRENS"]]					= 199,
	[L["STONETALON MOUNTAINS"]] 			= 65,
	[L["UN'GORO CRATER"]]					= 78,
	[L["WINTERSPRING"]]						= 83,
	-- Outlands
	[L["BLADE'S EDGE MOUNTAINS"]] 			= 105,
	[L["HELLFIRE PENINSULA"]] 				= 100,
	[L["NAGRAND (OUTLAND)"]] 				= 107,
	[L["NETHERSTORM"]] 						= 109,
	[L["SHADOWMOON VALLEY (OUTLAND)"]] 		= 104,
	[L["TEROKKAR FOREST"]] 					= 108,
	[L["ZANGARMARSH"]] 						= 102,
	-- Northrend
	[L["BOREAN TUNDRA"]]					= 114,
	[L["DRAGONBLIGHT"]]						= 115,
	[L["GRIZZLY HILLS"]]					= 116,
	[L["HOWLING FJORD"]]					= 117,
	[L["ICECROWN"]]							= 118,
	[L["SHOLAZAR BASIN"]]					= 119,
	[L["THE STORM PEAKS"]]					= 120,
	[L["ZUL'DRAK"]]							= 121,
	-- Pandaria
	[L["DREAD WASTES"]]						= 422,
	[L["KRASARANG WILDS"]]					= 418,
	[L["KUN-LAI SUMMIT"]]					= 379,
	[L["THE JADE FOREST"]]					= 371,
	[L["TOWNLONG STEPPES"]]					= 388,
	[L["VALE OF ETERNAL BLOSSOMS"]] 		= 390,
	[L["VALLEY OF THE FOUR WINDS"]] 		= 376,
	-- Draenor
	[L["FROSTFIRE RIDGE"]]					= 525,
	[L["GORGROND"]]							= 543,
	[L["NAGRAND"]]							= 550,
	[L["SHADOWMOON VALLEY"]]				= 539,
	[L["SPIRES OF ARAK"]]					= 542,
	[L["TALADOR"]]							= 535,
	-- Broken Isles
	[L["AZSUNA"]]							= 630,
	[L["HELHEIM"]]							= 649,
	[L["HIGHMOUNTAIN"]] 					= 650,
	[L["STORMHEIM"]]						= 634,
	[L["SURAMAR"]]							= 680,
	[L["VAL'SHARAH"]]						= 641,
	-- Kul Tiras
	[L["DRUSTVAR"]] 						= 896,
	[L["MECHAGON"]] 						= 1462,
	[L["NAZJATAR"]] 						= 1355,
	[L["STORMSONG VALLEY"]] 				= 942,
	[L["TIRAGARDE SOUND"]] 					= 895,
	-- Zandalar
	[L["NAZMIR"]] 							= 863,
	[L["VOL'DUN"]] 							= 864,
	[L["ZULDAZAR"]] 						= 862,
	-- Shadowlands
	[L["ARDENWEALD"]] 						= 1565,
	[L["BASTION"]] 							= 1533,
	[L["MALDRAXXUS"]] 						= 1536,
	[L["REVENDRETH"]] 						= 1525,
	[L["THE MAW"]] 							= 1543,
}

addonTable.maps = maps