local addonName, addonTable = ...

local maps = {
	-- Eastern Kingdoms
	["Arathi Highlands"] = 14,
	["Badlands"] = 15,
	["Blasted Lands"] = 17,
	["Burning Steppes"] = 36,
	["Dun Morogh"] = 27,
	["Duskwood"] = 47,
	["Eastern Plaguelands"] = 23,
	["Elwynn Forest"] = 37,
	["Eversong Woods"] = 94,
	["Ghostlands"] = 95,
	["Hillsbrad Foothills"] = 25,
	["Loch Modan"] = 48,
	["Northern Stranglethorn"] = 50,
	["Redridge Mountains"] = 49,
	["Searing Gorge"] = 32,
	["Silverpine Forest"] = 21,
	["The Cape of Stranglethorn"] = 210,
	["Tirisfal Glades"] = 18,
	["Western Plaguelands"] = 22,
	["Westfall"] = 52,
	["Wetlands"] = 56,
	-- Kalimdor
	["Ashenvale"] = 63,
	["Azshara"] = 76,
	["Darkshore"] = 62,
	["Desolace"] = 66,
	["Durotar"] = 1,
	["Dustwallow Marsh"] = 70,
	["Felwood"] = 77,
	["Feralas"] = 69,
	["Mulgore"] = 7,
	["Northern Barrens"] = 10,
	["Southern Barrens"] = 199,
	["Stonetalon Mountains"] = 65,
	["Un'Goro Crater"] = 78,
	["Winterspring"] = 83,
	-- Outland
	["Blade's Edge Mountains"] = 105,
	["Hellfire Peninsula"] = 100,
	["Nagrand (Outland)"] = 107,
	["Netherstorm"] = 109,
	["Shadowmoon Valley (Outland)"] = 104,
	["Terokkar Forest"] = 108,
	["Zangarmarsh"] = 102,
	-- Northrend
	["Borean Tundra"] = 114,
	["Dragonblight"] = 115,
	["Grizzly Hills"] = 116,
	["Howling Fjord"] = 117,
	["Icecrown"] = 118,
	["Sholazar Basin"] = 119,
	["The Storm Peaks"] = 120,
	["Zul'Drak"] = 121,
	-- Pandaria
	["Dread Wastes"] = 422,
	["Krasarang Wilds"] = 418,
	["Kun-Lai Summit"] = 379,
	["The Jade Forest"] = 371,
	["Townlong Steppes"] = 388,
	["Vale of Eternal Blossoms"] = 0,
	["Valley of the Four Winds"] = 376,
	-- Draenor
	["Frostfire Ridge"] = 525,
	["Gorgrond"] = 543,
	["Nagrand"] = 550,
	["Shadowmoon Valley"] = 539,
	["Spires of Arak"] = 542,
	["Talador"] = 535,
	-- Legion
	["Azsuna"] = 630,
	["Helheim"] = 649,
	["Highmountain"] = 650,
	["Stormheim"] = 634,
	["Suramar"] = 680,
	["Val'sharah"] = 641,
	-- Kul Tiras
	["Drustvar"] = 896,
	["Mechagon"] = 1462,
	["Nazjatar"] = 1355,
	["Stormsong Valley"] = 942,
	["Tiragarde Sound"] = 895,
	-- Zandalar
	["Nazmir"] = 863,
	["Vol'dun"] = 864,
	["Zuldazar"] = 862,
	-- Shadowlands
	["Ardenweald"] = 1565,
	["Bastion"] = 1533,
	["Maldraxxus"] = 1536,
	["Revendreth"] = 1525,
	["The Maw"] = 1543,
}

addonTable.maps = maps