local addonName, t = ...

local maps = {
	-- Eastern Kingdoms
	["Abyssal Depths"] = 0,
	["Arathi Highlands"] = 0,
	["Badlands"] = 0,
	["Blasted Lands"] = 0,
	["Burning Steppes"] = 0,
	["Deadwind Pass"] = 0,
	["Dun Morogh"] = 0,
	["Duskwood"] = 0,
	["Eastern Plaguelands"] = 0,
	["Elwynn Forest"] = 0,
	["Eversong Woods"] = 0,
	["Ghostlands"] = 0,
	["Gilneas"] = 0,
	["Gilneas City"] = 0,
	["Hillsbrad Foothills"] = 0,
	["Ironforge"] = 0,
	["Isle of Quel'Danas"] = 0,
	["Kelp'thar Forest"] = 0,
	["Loch Modan"] = 0,
	["Northern Stranglethorn"] = 0,
	["Redridge Mountains"] = 0,
	["Searing Gorge"] = 0,
	["Shimmering Expanse"] = 0,
	["Silverpine Forest"] = 0,
	["Swamp of Sorrows"] = 0,
	["The Cape of Stranglethorn Vale"] = 0,
	["The Hinterlands"] = 0,
	["Tirisfal Glades"] = 0,
	["Twilight Highlands"] = 0,
	["Western Plaguelands"] = 0,
	["Westfall"] = 0,
	["Wetlands"] = 0,
	-- Kalimdor
	["Ashenvale"] = 0,
	["Azshara"] = 0,
	["Azuremyst Isle"] = 0,
	["Bloodmyst Isle"] = 0,
	["Darkshore"] = 0,
	["Desolace"] = 0,
	["Durotar"] = 0,
	["Dustwallow Marsh"] = 0,
	["Felwood"] = 0,
	["Feralas"] = 0,
	["Mount Hyjal"] = 0,
	["Mulgore"] = 0,
	["Northern Barrens"] = 0,
	["Silithus"] = 0,
	["Southern Barrens"] = 0,
	["Stonetalon Mountains"] = 0,
	["Tanaris"] = 0,
	["Teldrassil"] = 0,
	["Thousand Needles"] = 0,
	["Uldum"] = 0,
	["Un'Goro Crater"] = 0,
	["Winterspring"] = 0,
	-- The Maelstrom
	["Deepholm"] = 0,
	["Kezan"] = 0,
	["The Lost Isles"] = 0,
	-- Outland
	["Blade's Edge Mountains"] = 0,
	["Hellfire Peninsula"] = 0,
	["Nagrand (Outland)"] = 0,
	["Netherstorm"] = 0,
	["Shadowmoon Valley (Outland)"] = 0,
	["Terokkar Forest"] = 0,
	["Zangarmarsh"] = 0,
	-- Northrend
	["Borean Tundra"] = 0,
	["Dragonblight"] = 115,
	["Grizzly Hills"] = 0,
	["Howling Fjord"] = 0,
	["Icecrown"] = 0,
	["Sholazar Basin"] = 0,
	["The Storm Peaks"] = 0,
	["Zul'Drak"] = 0,
	-- Pandaria
	["Dread Wastes"] = 0,
	["Krasarang Wilds"] = 0,
	["Kun-Lai Summit"] = 0,
	["The Jade Forest"] = 0,
	["Townlong Steppes"] = 0,
	["Vale of Eternal Blossoms"] = 0,
	["Valley of the Four Winds"] = 0,
	-- Draenor
	["Frostfire Ridge"] = 0,
	["Gorgrond"] = 0,
	["Nagrand"] = 0,
	["Shadowmoon Valley"] = 0,
	["Spires of Arak"] = 0,
	["Talador"] = 0,
	-- Legion
	["Argus"] = 0,
	["Azsuna"] = 0,
	["Highmountain"] = 0,
	["Stormheim"] = 0,
	["Suramar"] = 0,
	["Val'sharah"] = 0,
	-- Kul Tiras
	["Drustvar"] = 0,
	["Mechagon"] = 0,
	["Nazjatar"] = 1355,
	["Stormsong Valley"] = 0,
	["Tiragarde Sound"] = 0,
	-- Zandalar
	["Nazmir"] = 0,
	["Vol'dun"] = 0,
	["Zuldazar"] = 0,
	-- Shadowlands
	["Ardenweald"] = 0,
	["Bastion"] = 0,
	["Maldraxxus"] = 0,
	["Revendreth"] = 0,
	["The Maw"] = 1543,
}

t.maps = maps