local addonName, t = ...;

local quests = {
	[10] = { -- Northern Barrens
		["In Defense of Far Watch"] = {
			["id"] = 871,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Far Watch Offensive"] = {
			["id"] = 872,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Plainstrider Menace"] = {
			["id"] = 844,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Through Fire and Flames"] = {
			["id"] = 13878,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Supplies for the Crossroads"] = {
			["id"] = 5041,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Crossroads Caravan Pickup"] = {
			["id"] = 13949,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Drag it Out of Them"] = {
			["id"] = 13961,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Grol'dom Militia"] = {
			["id"] = 13973,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Consumed by Hatred"] = {
			["id"] = 899,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["By Hook Or By Crook"] = {
			["id"] = 13963,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Tortusk Takedown"] = {
			["id"] = 13968,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Grol'dom's Missing Kodo"] = {
			["id"] = 13969,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Animal Services"] = {
			["id"] = 13970,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Kodo's Return"] = {
			["id"] = 13971,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Crossroads Caravan Delivery"] = {
			["id"] = 13975,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Zhevra"] = {
			["id"] = 845,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Hunting the Huntress"] = {
			["id"] = 903,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Echeyakee"] = {
			["id"] = 881,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Into the Raptor's Den"] = {
			["id"] = 905,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Purloined Payroll"] = {
			["id"] = 13991,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Forgotten Pools"] = {
			["id"] = 870,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Kolkar Leaders"] = {
			["id"] = 850,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Little Diversion"] = {
			["id"] = 13992,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Growing Problem"] = {
			["id"] = 13988,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Stagnant Oasis"] = {
			["id"] = 877,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Altered Beings"] = {
			["id"] = 880,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["King of Centaur Mountain"] = {
			["id"] = 13995,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Flushing Out Verog"] = {
			["id"] = 14072,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Verog the Dervish"] = {
			["id"] = 851,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Fungal Spores"] = {
			["id"] = 848,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["In Fungus We Trust"] = {
			["id"] = 13998,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Who's Shroomin' Who?"] = {
			["id"] = 13999,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Deathgate's Reinforcements"] = {
			["id"] = 14073,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Centaur Bracers"] = {
			["id"] = 855,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Hezrul Bloodmark"] = {
			["id"] = 852,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Counterattack!"] = {
			["id"] = 4021,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Investigate the Wreckage"] = {
			["id"] = 14066,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["To Track a Thief"] = {
			["id"] = 869,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Stolen Silver"] = {
			["id"] = 14067,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Waptor Twapping"] = {
			["id"] = 14068,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Find Baron Longshore"] = {
			["id"] = 14045,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Baron's Demands"] = {
			["id"] = 14046,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Most Unusual Map"] = {
			["id"] = 14049,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Gazlowe's Fortune"] = {
			["id"] = 14050,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Raging River Ride"] = {
			["id"] = 26769,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Club Foote"] = {
			["id"] = 14034,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Love it or Limpet"] = {
			["id"] = 14038,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Ammo Kerblammo"] = {
			["id"] = 14042,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Captain's Vengeance"] = {
			["id"] = 891,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Take it up with Tony"] = {
			["id"] = 14052,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Glomp is Sitting On It"] = {
			["id"] = 14056,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Guns. We Need Guns."] = {
			["id"] = 14057,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Mutiny, Mon!"] = {
			["id"] = 14063,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Southsea Freebooters"] = {
			["id"] = 887,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["WANTED: Cap'n Garvey"] = {
			["id"] = 895,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["It's Gotta be the Horn"] = {
			["id"] = 865,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Samophlange"] = {
			["id"] = 29021,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Samophlange Repair"] = {
			["id"] = 14003,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Wenikee Boltbucket"] = {
			["id"] = 29026,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Nugget Slugs"] = {
			["id"] = 29027,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Burning Threat"] = {
			["id"] = 29090,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Return to Samophlanger"] = {
			["id"] = 14004,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Read the Manual"] = {
			["id"] = 14006,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Miner's Fortune"] = {
			["id"] = 29015,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Ignition"] = {
			["id"] = 858,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Escape"] = {
			["id"] = 863,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Sludge Investigation"] = {
			["id"] = 29087,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Hyena Extermination"] = {
			["id"] = 29088,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Sludge Beast!"] = {
			["id"] = 29089,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Short Way Home"] = {
			["id"] = 29094,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Harpy Raiders"] = {
			["id"] = 867,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Harpy Lieutenants"] = {
			["id"] = 875,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Serena Bloodfeather"] = { -- Auto Accepted
			["id"] = 876,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Report to Thork"] = {
			["id"] = 29095,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Mor'shan Caravan Pick-Up"] = {
			["id"] = 29109,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Mor'shan Caravan Rescue"] = {
			["id"] = 29110,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Demon Seed"] = {
			["id"] = 29112,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Mor'shan Caravan Delivery"] = {
			["id"] = 29111,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
	},
	[21] = { -- Silverpine Forest
		["The Warchief Cometh"] = {
			["id"] = 26965,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Warchief's Command: Hillsbrad Foothills!"] = {
			["id"] = 28089,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Guts and Gore"] = {
			["id"] = 26995,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Gilneas Liberation Front"] = {
			["id"] = 26989,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Agony Abounds"] = {
			["id"] = 26992,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Iterating Upon Success"] = {
			["id"] = 26998,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Dangerous Intentions"] = {
			["id"] = 27039,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Waiting to Exsanguinate"] = {
			["id"] = 27045,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Belmont's Report"] = {
			["id"] = 27056,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Warchief's Fleet"] = {
			["id"] = 27065,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Steel Thunder"] = {
			["id"] = 27069,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Give 'em Hell!"] = {
			["id"] = 27073,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Playing Dirty"] = {
			["id"] = 27082,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["It's Only Poisonous if You Ingest It"] = {
			["id"] = 27088,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Lost in the Darkness"] = {
			["id"] = 27093,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Skitterweb Menace"] = {
			["id"] = 27095,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Deeper into Darkness"] = { -- Auto Accepted
			["id"] = 27094,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Orcs are in Order"] = {
			["id"] = 27096,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = t.flightPaths["Forsaken High Command, Silverpine Forest"],
		},
		["Rise, Forsaken"] = {
			["id"] = 27097,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["No Escape"] = { -- Auto Accepted
			["id"] = 27099,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Lordaeron"] = {
			["id"] = 27098,
			["reward"] = 0,
			["cancelCinematic"] = true,
			["flightPath"] = nil,
		},
		["Honor the Dead"] = {
			["id"] = 27180,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Hair of the Dog"] = {
			["id"] = 27226,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Reinforcements from Fenris"] = {
			["id"] = 27231,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Excising the Taint"] = { -- Auto Accepted
			["id"] = 27181,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Seek and Destroy"] = { -- Auto Accepted
			["id"] = 27193,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Cornered and Crushed!"] = { -- Auto Accepted
			["id"] = 27194,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Nowhere to Run"] = {
			["id"] = 27195,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Waters Run Red..."] = {
			["id"] = 27232,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["To Forsaken Forward Command"] = {
			["id"] = 27290,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["In Time, All Will Be Revealed"] = {
			["id"] = 27342,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Losing Ground"] = {
			["id"] = 27333,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The F.C.D."] = {
			["id"] = 27345,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Korok the Colossus"] = { -- Drops from Korok the Colossus, Starts from an Item
			["id"] = 27322,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Break in Communications: Dreadwatch Outpost"] = {
			["id"] = 27349,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Break in Communications: Rutsak's Outpost"] = { -- Auto Accepted
			["id"] = 27350,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Vengeance for Our Soldiers"] = {
			["id"] = 27360,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["On Whose Orders?"] = { -- Auto Accepted
			["id"] = 27364,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["What Tomorrow Brings"] = { -- Auto Accepted
			["id"] = 27401,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Fall Back!"] = {
			["id"] = 27405,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Man Named Godfrey"] = {
			["id"] = 27406,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Resistance is Futile"] = { -- Auto Accepted
			["id"] = 27423,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Great Escape"] = {
			["id"] = 27438,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Rise, Godfrey"] = {
			["id"] = 27472,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Breaking the Barrier"] = {
			["id"] = 27474,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		[""] = {
			["id"] = ,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Unyielding Servitors"] = {
			["id"] = 27475,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Dalar Dawnweaver"] = {
			["id"] = 27476,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Relios the Relic Keeper"] = {
			["id"] = 27478,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Practical Vengeance"] = {
			["id"] = 27483,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Ley Energies"] = { -- Drops from Arcane Remnants, Starts from an Item
			["id"] = 27480,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Only One May Enter"] = {
			["id"] = 27484,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Transdimensional Warfare: Chapter I"] = {
			["id"] = 27512,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Wolf in Bear's Clothing"] = {
			["id"] = 27510,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Transdimensional Warfare: Chapter II"] = {
			["id"] = 27513,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Transdimensional Warfare: Chapter III"] = { -- Auto Accepted
			["id"] = 27518,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Taking the Battlefront"] = {
			["id"] = 27542,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Pyrewood's Fall"] = {
			["id"] = 27550,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Lessons in Fear"] = {
			["id"] = 27548,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Of No Consequence"] = {
			["id"] = 27547,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["I Never Forget a Face"] = { -- Drops from Marsh Crocolisks, Starts from an Item
			["id"] = 27574,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["From the Belly of the Beast"] = {
			["id"] = 27575,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["7th Legion Battle Plans"] = {
			["id"] = 27577,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Sowing Discord"] = {
			["id"] = 27580,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
	},
	[22] = { -- Western Plaguelands
		["Scourge First... Alliance Later"] = {
			["id"] = 26921,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Endless Flow"] = {
			["id"] = 26922,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["War Machines"] = {
			["id"] = 26923,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Scholomancer"] = {
			["id"] = 26924,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Araj the Summoner"] = {
			["id"] = 26925,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Brute Strength"] = {
			["id"] = 27117,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Victory, For Now"] = {
			["id"] = 26926,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["After the Crusade"] = {
			["id"] = 26930,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Foxes and Hounds"] = {
			["id"] = 26931,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Foes Before Hoes"] = {
			["id"] = 26933,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Latent Disease"] = {
			["id"] = 26934,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Who Needs Cauldrons?"] = {
			["id"] = 26978,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Menders' Stead"] = {
			["id"] = 26952,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A New Era for the Plaguelands"] = {
			["id"] = 26999,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["I Ain't Sayin' You a Gourd-Digger..."] = {
			["id"] = 26956,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Zen'Kiki, the Druid"] = {
			["id"] = 26953,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Different Approach"] = {
			["id"] = 26954,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Northridge Lumber Mill"] = {
			["id"] = 26935,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Learning the Ropes"] = {
			["id"] = 27000,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Too Close for Comfort"] = {
			["id"] = 27013,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["This Means WAR (Wild Arachnid Roundup)"] = {
			["id"] = 27001,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Redpine Thievery"] = {
			["id"] = 27011,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Gnoll's Resolve"] = {
			["id"] = 27012,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
	},
	[25] = { -- Hillsbrad Foothills
		["Welcome to the Machine"] = {
			["id"] = 28096,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Trouble at Azurelode"] = {
			["id"] = 28111,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Glorious Harvest"] = {
			["id"] = 28114,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Past Their Prime"] = {
			["id"] = 28115,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Human Infestation"] = {
			["id"] = 28138,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Thieving Little Monsters!"] = {
			["id"] = 28144,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Coastal Delicacies"] = {
			["id"] = 28146,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Muckgill's Flipper or Something..."] = { -- Drops from Muckgill, Starts from an Item
			["id"] = 28154,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Deep Mine Rescue"] = {
			["id"] = 28156,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Trouble at the Sludge Fields"] = {
			["id"] = 28168,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["No One Here Gets Out Alive"] = {
			["id"] = 28192,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Discretion is Key"] = {
			["id"] = 28197,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["For Science!"] = {
			["id"] = 28199,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Battle for Hillsbrad"] = { -- Drops from Clerk Horrace Whitesteed, Starts from an Item.
			["id"] = 28196,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Do the Right Thing"] = {
			["id"] = 28189,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Little Girl Lost"] = {
			["id"] = 28206,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Freedom for Lydon"] = {
			["id"] = 28209,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Protocol"] = {
			["id"] = 28230,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Do it for Twinkles"] = {
			["id"] = 28231,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Burnside Must Fall"] = {
			["id"] = 28235,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Blight Upon the Land"] = {
			["id"] = 28237,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Trouble at Southshore"] = {
			["id"] = 28251,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Studies in Lethality"] = {
			["id"] = 28324,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Green Living"] = {
			["id"] = 28325,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Helcular's Rod Giveth..."] = {
			["id"] = 28331,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Helcular's Command"] = {
			["id"] = 28332,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Angry Scrubbing Bubbles"] = { -- Auto Accepted
			["id"] = 28329,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Trail of Filth"] = {
			["id"] = 28330,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Can You Smell What the Lok'tar is Cooking?"] = {
			["id"] = 28344,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["*Gurgle* HELP! *Gurgle*"] = {
			["id"] = 28345,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Stormpike Rendezvous"] = {
			["id"] = 28348,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Preemptive Strike"] = { -- Drops from Daggerspine Naga, Starts from an Item.
			["id"] = 28356,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Kasha Will Fly Again"] = {
			["id"] = 28354,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Terrible Little Creatures"] = {
			["id"] = 28355,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Road to Purgation"] = {
			["id"] = 28375,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
	},
	[65] = { -- Stonetalon Mountains
	
	},
	[70] = { -- Dustwallow Marsh
	
	},
	[199] = { -- Southern Barrens
	
	},
};

t.quests = quests;