local addonName, t = ...;

local quests = {
	[10] = { -- Northern Barrens
		["In Defense of Far Watch"] = {
			["id"] = 871,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Far Watch Offensive"] = {
			["id"] = 872,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Plainstrider Menace"] = {
			["id"] = 844,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Through Fire and Flames"] = {
			["id"] = 13878,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Supplies for the Crossroads"] = {
			["id"] = 5041,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Crossroads Caravan Pickup"] = {
			["id"] = 13949,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Drag it Out of Them"] = {
			["id"] = 13961,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Grol'dom Militia"] = {
			["id"] = 13973,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Consumed by Hatred"] = {
			["id"] = 899,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["By Hook Or By Crook"] = {
			["id"] = 13963,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Tortusk Takedown"] = {
			["id"] = 13968,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Grol'dom's Missing Kodo"] = {
			["id"] = 13969,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Animal Services"] = {
			["id"] = 13970,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Kodo's Return"] = {
			["id"] = 13971,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Crossroads Caravan Delivery"] = {
			["id"] = 13975,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Zhevra"] = {
			["id"] = 845,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Hunting the Huntress"] = {
			["id"] = 903,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Echeyakee"] = {
			["id"] = 881,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Into the Raptor's Den"] = {
			["id"] = 905,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Purloined Payroll"] = {
			["id"] = 13991,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Forgotten Pools"] = {
			["id"] = 870,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Kolkar Leaders"] = {
			["id"] = 850,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Little Diversion"] = {
			["id"] = 13992,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Growing Problem"] = {
			["id"] = 13988,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Stagnant Oasis"] = {
			["id"] = 877,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Altered Beings"] = {
			["id"] = 880,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["King of Centaur Mountain"] = {
			["id"] = 13995,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Flushing Out Verog"] = {
			["id"] = 14072,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Verog the Dervish"] = {
			["id"] = 851,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Fungal Spores"] = {
			["id"] = 848,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["In Fungus We Trust"] = {
			["id"] = 13998,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Who's Shroomin' Who?"] = {
			["id"] = 13999,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Deathgate's Reinforcements"] = {
			["id"] = 14073,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Centaur Bracers"] = {
			["id"] = 855,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Hezrul Bloodmark"] = {
			["id"] = 852,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Counterattack!"] = {
			["id"] = 4021,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Investigate the Wreckage"] = {
			["id"] = 14066,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["To Track a Thief"] = {
			["id"] = 869,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Stolen Silver"] = {
			["id"] = 14067,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Waptor Twapping"] = {
			["id"] = 14068,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Find Baron Longshore"] = {
			["id"] = 14045,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Baron's Demands"] = {
			["id"] = 14046,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Most Unusual Map"] = {
			["id"] = 14049,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Gazlowe's Fortune"] = {
			["id"] = 14050,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Raging River Ride"] = {
			["id"] = 26769,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Club Foote"] = {
			["id"] = 14034,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Love it or Limpet"] = {
			["id"] = 14038,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Ammo Kerblammo"] = {
			["id"] = 14042,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Captain's Vengeance"] = {
			["id"] = 891,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Take it up with Tony"] = {
			["id"] = 14052,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Glomp is Sitting On It"] = {
			["id"] = 14056,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Guns. We Need Guns."] = {
			["id"] = 14057,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Mutiny, Mon!"] = {
			["id"] = 14063,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Southsea Freebooters"] = {
			["id"] = 887,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["WANTED: Cap'n Garvey"] = {
			["id"] = 895,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["It's Gotta be the Horn"] = {
			["id"] = 865,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Samophlange"] = {
			["id"] = 29021,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Samophlange Repair"] = {
			["id"] = 14003,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Wenikee Boltbucket"] = {
			["id"] = 29026,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Nugget Slugs"] = {
			["id"] = 29027,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Burning Threat"] = {
			["id"] = 29090,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Return to Samophlanger"] = {
			["id"] = 14004,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Read the Manual"] = {
			["id"] = 14006,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Miner's Fortune"] = {
			["id"] = 29015,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Ignition"] = {
			["id"] = 858,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Escape"] = {
			["id"] = 863,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Sludge Investigation"] = {
			["id"] = 29087,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Hyena Extermination"] = {
			["id"] = 29088,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Sludge Beast!"] = {
			["id"] = 29089,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Short Way Home"] = {
			["id"] = 29094,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Harpy Raiders"] = {
			["id"] = 867,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Harpy Lieutenants"] = {
			["id"] = 875,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Serena Bloodfeather"] = { -- Auto Accepted
			["id"] = 876,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Report to Thork"] = {
			["id"] = 29095,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Mor'shan Caravan Pick-Up"] = {
			["id"] = 29109,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Mor'shan Caravan Rescue"] = {
			["id"] = 29110,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Demon Seed"] = {
			["id"] = 29112,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Mor'shan Caravan Delivery"] = {
			["id"] = 29111,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
	},
	[18] = { -- Tirisfal Glades
		["After the Crusade"] = {
			["id"] = 26930,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Foxes and Hounds"] = {
			["id"] = 26931,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Foes Before Hoes"] = {
			["id"] = 26933,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Latent Disease"] = {
			["id"] = 26934,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Who Needs Cauldrons?"] = {
			["id"] = 26978,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Menders' Stead"] = {
			["id"] = 26952,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
	},
	[21] = { -- Silverpine Forest
		["The Warchief Cometh"] = {
			["id"] = 26965,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Warchief's Command: Hillsbrad Foothills!"] = {
			["id"] = 28089,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Guts and Gore"] = {
			["id"] = 26995,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Gilneas Liberation Front"] = {
			["id"] = 26989,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Agony Abounds"] = {
			["id"] = 26992,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Iterating Upon Success"] = {
			["id"] = 26998,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Dangerous Intentions"] = {
			["id"] = 27039,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Waiting to Exsanguinate"] = {
			["id"] = 27045,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Belmont's Report"] = {
			["id"] = 27056,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Warchief's Fleet"] = {
			["id"] = 27065,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Steel Thunder"] = {
			["id"] = 27069,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Give 'em Hell!"] = {
			["id"] = 27073,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Playing Dirty"] = {
			["id"] = 27082,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["It's Only Poisonous if You Ingest It"] = {
			["id"] = 27088,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Lost in the Darkness"] = {
			["id"] = 27093,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Skitterweb Menace"] = {
			["id"] = 27095,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Deeper into Darkness"] = { -- Auto Accepted
			["id"] = 27094,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Orcs are in Order"] = {
			["id"] = 27096,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = t.flightPaths["Forsaken High Command, Silverpine Forest"],
		},
		["Rise, Forsaken"] = {
			["id"] = 27097,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["No Escape"] = { -- Auto Accepted
			["id"] = 27099,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Lordaeron"] = {
			["id"] = 27098,
			["reward"] = 0,
			["cancelCinematic"] = true,
			["flightPath"] = nil,
		},
		["Honor the Dead"] = {
			["id"] = 27180,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Hair of the Dog"] = {
			["id"] = 27226,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Reinforcements from Fenris"] = {
			["id"] = 27231,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Excising the Taint"] = { -- Auto Accepted
			["id"] = 27181,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Seek and Destroy"] = { -- Auto Accepted
			["id"] = 27193,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Cornered and Crushed!"] = { -- Auto Accepted
			["id"] = 27194,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Nowhere to Run"] = {
			["id"] = 27195,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Waters Run Red..."] = {
			["id"] = 27232,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["To Forsaken Forward Command"] = {
			["id"] = 27290,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["In Time, All Will Be Revealed"] = {
			["id"] = 27342,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Losing Ground"] = {
			["id"] = 27333,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The F.C.D."] = {
			["id"] = 27345,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Korok the Colossus"] = { -- Drops from Korok the Colossus, Starts from an Item
			["id"] = 27322,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Break in Communications: Dreadwatch Outpost"] = {
			["id"] = 27349,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Break in Communications: Rutsak's Outpost"] = { -- Auto Accepted
			["id"] = 27350,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Vengeance for Our Soldiers"] = {
			["id"] = 27360,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["On Whose Orders?"] = { -- Auto Accepted
			["id"] = 27364,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["What Tomorrow Brings"] = { -- Auto Accepted
			["id"] = 27401,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Fall Back!"] = {
			["id"] = 27405,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Man Named Godfrey"] = {
			["id"] = 27406,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Resistance is Futile"] = { -- Auto Accepted
			["id"] = 27423,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Great Escape"] = {
			["id"] = 27438,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Rise, Godfrey"] = {
			["id"] = 27472,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Breaking the Barrier"] = {
			["id"] = 27474,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Unyielding Servitors"] = {
			["id"] = 27475,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Dalar Dawnweaver"] = {
			["id"] = 27476,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Relios the Relic Keeper"] = {
			["id"] = 27478,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Practical Vengeance"] = {
			["id"] = 27483,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Ley Energies"] = { -- Drops from Arcane Remnants, Starts from an Item
			["id"] = 27480,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Only One May Enter"] = {
			["id"] = 27484,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Transdimensional Warfare: Chapter I"] = {
			["id"] = 27512,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Wolf in Bear's Clothing"] = {
			["id"] = 27510,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Transdimensional Warfare: Chapter II"] = {
			["id"] = 27513,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Transdimensional Warfare: Chapter III"] = { -- Auto Accepted
			["id"] = 27518,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Taking the Battlefront"] = {
			["id"] = 27542,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Pyrewood's Fall"] = {
			["id"] = 27550,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Lessons in Fear"] = {
			["id"] = 27548,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Of No Consequence"] = {
			["id"] = 27547,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["I Never Forget a Face"] = { -- Drops from Marsh Crocolisks, Starts from an Item
			["id"] = 27574,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["From the Belly of the Beast"] = {
			["id"] = 27575,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["7th Legion Battle Plans"] = {
			["id"] = 27577,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Sowing Discord"] = {
			["id"] = 27580,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
	},
	[22] = { -- Western Plaguelands
		["Scourge First... Alliance Later"] = {
			["id"] = 26921,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Endless Flow"] = {
			["id"] = 26922,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["War Machines"] = {
			["id"] = 26923,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Scholomancer"] = {
			["id"] = 26924,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Araj the Summoner"] = {
			["id"] = 26925,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Brute Strength"] = {
			["id"] = 27117,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Victory, For Now"] = {
			["id"] = 26926,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A New Era for the Plaguelands"] = {
			["id"] = 26999,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["I Ain't Sayin' You a Gourd-Digger..."] = {
			["id"] = 26956,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Zen'Kiki, the Druid"] = {
			["id"] = 26953,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Different Approach"] = {
			["id"] = 26954,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Northridge Lumber Mill"] = {
			["id"] = 26935,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Learning the Ropes"] = {
			["id"] = 27000,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Too Close for Comfort"] = {
			["id"] = 27013,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["This Means WAR (Wild Arachnid Roundup)"] = {
			["id"] = 27001,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Redpine Thievery"] = {
			["id"] = 27011,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Gnoll's Resolve"] = {
			["id"] = 27012,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
	},
	[25] = { -- Hillsbrad Foothills
		["Welcome to the Machine"] = {
			["id"] = 28096,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Trouble at Azurelode"] = {
			["id"] = 28111,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Glorious Harvest"] = {
			["id"] = 28114,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Past Their Prime"] = {
			["id"] = 28115,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Human Infestation"] = {
			["id"] = 28138,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Thieving Little Monsters!"] = {
			["id"] = 28144,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Coastal Delicacies"] = {
			["id"] = 28146,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Muckgill's Flipper or Something..."] = { -- Drops from Muckgill, Starts from an Item
			["id"] = 28154,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Deep Mine Rescue"] = {
			["id"] = 28156,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Trouble at the Sludge Fields"] = {
			["id"] = 28168,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["No One Here Gets Out Alive"] = {
			["id"] = 28192,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Discretion is Key"] = {
			["id"] = 28197,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["For Science!"] = {
			["id"] = 28199,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Battle for Hillsbrad"] = { -- Drops from Clerk Horrace Whitesteed, Starts from an Item.
			["id"] = 28196,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Do the Right Thing"] = {
			["id"] = 28189,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Little Girl Lost"] = {
			["id"] = 28206,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Freedom for Lydon"] = {
			["id"] = 28209,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Protocol"] = {
			["id"] = 28230,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Do it for Twinkles"] = {
			["id"] = 28231,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Burnside Must Fall"] = {
			["id"] = 28235,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Blight Upon the Land"] = {
			["id"] = 28237,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Trouble at Southshore"] = {
			["id"] = 28251,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Studies in Lethality"] = {
			["id"] = 28324,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Green Living"] = {
			["id"] = 28325,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Helcular's Rod Giveth..."] = {
			["id"] = 28331,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Helcular's Command"] = {
			["id"] = 28332,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Angry Scrubbing Bubbles"] = { -- Auto Accepted
			["id"] = 28329,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Trail of Filth"] = {
			["id"] = 28330,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Can You Smell What the Lok'tar is Cooking?"] = {
			["id"] = 28344,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["*Gurgle* HELP! *Gurgle*"] = {
			["id"] = 28345,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Stormpike Rendezvous"] = {
			["id"] = 28348,
			["reward"] = 0,
			["cancelCinematic"] = true,
			["flightPath"] = nil,
		},
		["Preemptive Strike"] = { -- Drops from Daggerspine Naga, Starts from an Item.
			["id"] = 28356,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Kasha Will Fly Again"] = {
			["id"] = 28354,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Terrible Little Creatures"] = {
			["id"] = 28355,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Road to Purgation"] = {
			["id"] = 28375,
			["reward"] = 0,
			["cancelCinematic"] = true,
			["flightPath"] = nil,
		},
	},
	[63] = { -- Ashenvale
		["We're Here to Do One Thing, Maybe Two..."] = {
			["id"] = 25945,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
	},
	[65] = { -- Stonetalon Mountains
		["Barrier to Entry"] = {
			["id"] = 25999,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Lessons from the Lost Isles"] = {
			["id"] = 26003,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Missing Blastgineer"] = {
			["id"] = 26001,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Alliance Attack Plans"] = {
			["id"] = 26002,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Krom'gar Fortress"] = {
			["id"] = 26004,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Ashes to Ashes"] = {
			["id"] = 26010,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Might of the Krom'gar"] = {
			["id"] = 28084,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Dream of a Better Tomorrow"] = {
			["id"] = 26026,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Enemy of the Horde: Marshal Paltrow"] = {
			["id"] = 26011,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["BEWARE OF CRAGJAW!"] = {
			["id"] = 26043,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Mr. D's Wild Ride"] = {
			["id"] = 26028,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Orders from Base Camp"] = { -- Drops from Marshal Paltrow, Starts from an Item.
			["id"] = 26016,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Report to Bombgutz"] = {
			["id"] = 26020,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Where Are the Parts?"] = {
			["id"] = 26044,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["I Got Your Parts Right Here..."] = {
			["id"] = 26045,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Between a Rock and a Hard Place"] = {
			["id"] = 26046,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["And That's Why They Call Them Peons..."] = {
			["id"] = 26047,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Spare Parts Up In Here!"] = {
			["id"] = 26048,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["In Defense of Krom'gar Fortress"] = {
			["id"] = 26058,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Eyes and Ears: Malaka'jin"] = {
			["id"] = 26059,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Queen and Her Court"] = {
			["id"] = 26063,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Da Voodoo: Stormer Heart"] = {
			["id"] = 26060,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Da Voodoo: Ram Horns"] = {
			["id"] = 26061,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Fight on Their Stomachs"] = {
			["id"] = 26064,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Da Voodoo: Resonite Crystal"] = {
			["id"] = 26062,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Jin'Zil's Blessing"] = {
			["id"] = 26067,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Nura Pathfinder"] = {
			["id"] = 26069,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Reinforcements..."] = {
			["id"] = 26066,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Kobold Fury"] = {
			["id"] = 26068,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["All's Quiet on the Southern Front"] = {
			["id"] = 26073,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Beginning of the End"] = {
			["id"] = 26074,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Turd Problem"] = {
			["id"] = 26075,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Spy Infestation"] = {
			["id"] = 26076,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Final Delivery"] = {
			["id"] = 26077,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["To Battlescar!"] = {
			["id"] = 26082,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Proof of Lies"] = {
			["id"] = 26097,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Betrayal at the Grove"] = {
			["id"] = 26098,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Is This Justice?"] = {
			["id"] = 26099,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The General is Dead"] = {
			["id"] = 26100,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
	},
	[70] = { -- Dustwallow Marsh
		["The Black Shield"] = {
			["id"] = 27254,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Suspicious Hoofprints"] = {
			["id"] = 27259,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Lieutenant Paval Reethe"] = {
			["id"] = 27260,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Theramore Spies"] = {
			["id"] = 1201,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Theramore Docks"] = {
			["id"] = 1202,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Hermit of Witch Hill"] = {
			["id"] = 27182,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Shambling Threat"] = {
			["id"] = 26682,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Darkmist Extermination"] = {
			["id"] = 25051,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["SMASH BROODQUEEN"] = {
			["id"] = 27229,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Black Shield"] = {
			["id"] = 27255,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Twilight of the Dawn Runner"] = {
			["id"] = 9437,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Lost Report"] = {
			["id"] = 27244,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Marsh Frog Legs"] = {
			["id"] = 27183,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["What's Haunting Witch Hill?"] = {
			["id"] = 27188,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Witch's Bane"] = {
			["id"] = 27189,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Jarl Needs Eyes"] = {
			["id"] = 27184,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Hungry as an Ogre!"] = {
			["id"] = 27191,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Jarl Needs a Blade"] = {
			["id"] = 27186,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
	},
	[85] = { -- Orgrimmar
		["Warlords of Draenor: The Dark Portal"] = {
			["id"] = 34398,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
	},
	[199] = { -- Southern Barrens
		["Clear the High Road"] = {
			["id"] = 24504,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Warriors' Redemption"] = {
			["id"] = 24512,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Feeding the Fear"] = {
			["id"] = 25284,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Holdout at Hunter's Hill"] = {
			["id"] = 24505,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Raptor Scraps"] = {
			["id"] = 24514,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Put the Fear in Them"] = {
			["id"] = 24517,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Low Road"] = { -- Drops from an Honor's Stand Officer, Starts from an Item.
			["id"] = 24518,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Stalling the Survey"] = {
			["id"] = 24519,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Signals in the Sky"] = {
			["id"] = 24515,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Keeping the Dogs at Bay"] = {
			["id"] = 24525,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Bad to Worse"] = {
			["id"] = 24529,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["When Plants Attack"] = {
			["id"] = 24539,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Curious Bloom"] = {
			["id"] = 24542,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Speaking Their Language"] = {
			["id"] = 24534,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Family Divided"] = {
			["id"] = 24543,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Biological Intervention"] = {
			["id"] = 24565,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Adder Subtraction"] = {
			["id"] = 24570,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Lashvine Seeds"] = {
			["id"] = 24571,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Sowing a Solution"] = {
			["id"] = 24566,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["To Harvest Chaos"] = {
			["id"] = 24574,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Nightmare Scar"] = {
			["id"] = 24601,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Winnoa Pineforest"] = {
			["id"] = 24807,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Lion's Pride"] = {
			["id"] = 24552,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Meet the New Boss"] = {
			["id"] = 24551,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Line in the Dirt"] = {
			["id"] = 24546,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Siegebreaker"] = {
			["id"] = 24569,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Honoring the Dead"] = {
			["id"] = 24573,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Taking Back Taurajo"] = {
			["id"] = 24572,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Desolation Hold Inspection"] = {
			["id"] = 24577,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = t.flightPaths["Desolation Hold, Southern Barrens"],
		},
		["Changing of the Gar'dul"] = {
			["id"] = 24591,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Parts-is-Parts"] = {
			["id"] = 24619,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Hearts-is-Hearts"] = {
			["id"] = 24620,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Smarts-is-Smarts"] = {
			["id"] = 24621,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Claim the Battle Scar"] = {
			["id"] = 24618,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Silithissues"] = {
			["id"] = 24654,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Firestone Point"] = {
			["id"] = 24667,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Intelligence Warfare"] = {
			["id"] = 24634,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Butcher of Taurajo"] = {
			["id"] = 24637,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Flightmare"] = {
			["id"] = 24631,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Tauren Vengeance"] = {
			["id"] = 24632,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Disturbed Earth"] = {
			["id"] = 24824,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Feeling Thorny"] = {
			["id"] = 26908,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Concern for Mankrik"] = {
			["id"] = 24604,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Mahka's Plea"] = {
			["id"] = 24633,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Don't Stop Bereavin'"] = {
			["id"] = 24603,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Mangletooth"] = {
			["id"] = 24608,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Blood of the Barrens"] = { -- Drops from the Quilboar, Starts from an Item.
			["id"] = 24606,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Echoes of Agamaggan"] = {
			["id"] = 24653,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Weezil in the Henhouse"] = {
			["id"] = 24684,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Dwarf Fortress"] = {
			["id"] = 24685,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Sabotage!"] = {
			["id"] = 24747,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Next of Kin"] = {
			["id"] = 25292,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
	},
	[525] = { -- Frostfire Ridge
		["The Home of the Frostwolves"] = {
			["id"] = 33868,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Song of Frost and Fire"] = {
			["id"] = 33815,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Of Wolves and Warriors"] = {
			["id"] = 34402,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["For the Horde!"] = {
			["id"] = 34364,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Back to Work"] = {
			["id"] = 34375,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Gronnling Problem"] = {
			["id"] = 34592,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Den of Skog"] = {
			["id"] = 34765,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Establish Your Garrison"] = {
			["id"] = 34378,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["What We Need"] = {
			["id"] = 34822,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["What We Got"] = {
			["id"] = 37824,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Build Your Barracks"] = {
			["id"] = 34461,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["We Need An Army"] = {
			["id"] = 34861,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Winds of Change"] = {
			["id"] = 34462,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Mission Probable"] = {
			["id"] = 34775,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
	},
	[572] = { -- Draenor (Cosmic)
		["Azeroth's Last Stand"] = {
			["id"] = 35933,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Onslaught's End"] = {
			["id"] = 34392,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Portal's Power"] = {
			["id"] = 34393,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Cost of War"] = {
			["id"] = 34420,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Blaze of Glory"] = {
			["id"] = 34422,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Bled Dry"] = {
			["id"] = 34421,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Vengeance for the Fallen"] = {
			["id"] = 35241,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Altar Altercation"] = {
			["id"] = 34423,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Kargathar Proving Grounds"] = {
			["id"] = 34425,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Potential Ally"] = {
			["id"] = 34427,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Kill Your Hundred"] = {
			["id"] = 34429,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Masters of Shadow"] = {
			["id"] = 34737,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Shadowmoon Clan"] = {
			["id"] = 34739,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Yrel"] = {
			["id"] = 34740,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Keli'dan the Breaker"] = {
			["id"] = 34741,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Prepare for Battle"] = {
			["id"] = 35005,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Battle of the Forge"] = {
			["id"] = 34439,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Ga'nar of the Frostwolf"] = {
			["id"] = 34442,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Gunpowder Plot"] = {
			["id"] = 34987,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Shadow of the Worldbreaker"] = {
			["id"] = 34958,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Polishing the Iron Throne"] = {
			["id"] = 34925,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Prodigal Frostwolf"] = {
			["id"] = 34437,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["Taking a Trip to the Top of the Tank"] = {
			["id"] = 35747,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["A Taste of Iron"] = {
			["id"] = 34445,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
		["The Home Stretch"] = {
			["id"] = 34446,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPath"] = nil,
		},
	},
};

t.quests = quests;