local addonName, t = ...;

local ids = {
	["In Defense of Far Watch"] = 871,
	["The Far Watch Offensive"] = 872,
	["Plainstrider Menace"] = 844,
	["Through Fire and Flames"] = 13878,
	["Supplies for the Crossroads"] = 5041,
	["Crossroads Caravan Pickup"] = 13949,
	["Drag it Out of Them"] = 13961,
	["The Grol'dom Militia"] = 13973,
	["Consumed by Hatred"] = 899,
	["By Hook Or By Crook"] = 13963,
	["The Tortusk Takedown"] = 13968,
	["Grol'dom's Missing Kodo"] = 13969,
	["Animal Services"] = 13970,
	["The Kodo's Return"] = 13971,
	["Crossroads Caravan Delivery"] = 13975,
	["The Zhevra"] = 845,
	["Hunting the Huntress"] = 903,
	["Echeyakee"] = 881,
	["Into the Raptor's Den"] = 905,
	["The Purloined Payroll"] = 13991,
	["The Forgotten Pools"] = 870,
	["Kolkar Leaders"] = 850,
	["A Little Diversion"] = 13992,
	["A Growing Problem"] = 13988,
	["The Stagnant Oasis"] = 877,
	["King of Centaur Mountain"] = 13995,
	["Altered Beings"] = 880,
	["Flushing Out Verog"] = 14072,
	["Verog the Dervish"] = 851,
	["Deathgate's Reinforcements"] = 14073,
	["Fungal Spores"] = 848,
	["In Fungus We Trust"] = 13998,
	["Who's Shroomin' Who?"] = 13999,
	["Centaur Bracers"] = 855,
	["Hezrul Bloodmark"] = 852,
	["Counterattack!"] = 4021,
	["Investigate the Wreckage"] = 14066,
	["To Track a Thief"] = 869,
	["The Stolen Silver"] = 14067,
	["Waptor Twapping"] = 14068,
	["Find Baron Longshore"] = 14045,
	["The Baron's Demands"] = 14046,
	["A Most Unusual Map"] = 14049,
	["Gazlowe's Fortune"] = 14050,
	["Raging River Ride"] = 26769,
	["Club Foote"] = 14034,
	["Love it or Limpet"] = 14038,
	["Ammo Kerblammo"] = 14042,
	["A Captain's Vengeance"] = 891,
	["Take it up with Tony"] = 14052,
	["Glomp is Sitting On It"] = 14056,
	["Guns. We Need Guns."] = 14057,
	["Mutiny, Mon!"] = 14063,
	["Southsea Freebooters"] = 887,
	["WANTED: Cap'n Garvey"] = 895,
	["It's Gotta be the Horn"] = 865,
	["Samophlange"] = 29021,
	["Competition Schmompetition"] = 29086,
	["Samophlange Repair"] = 14003,
	["Wenikee Boltbucket"] = 29026,
	["Nugget Slugs"] = 29027,
	["A Burning Threat"] = 29090,
	["Return to Samophlanger"] = 14004,
	["Read the Manual"] = 14006,
	["Miner's Fortune"] = 29015,
	["Ignition"] = 858,
	["The Escape"] = 863,
	["Sludge Investigation"] = 29087,
	["Hyena Extermination"] = 29088,
	["Sludge Beast!"] = 29089,
	["The Short Way Home"] = 29094,
	["Harpy Raiders"] = 867,
	["Harpy Lieutenants"] = 875,
	["Serena Bloodfeather"] = 876,
	["Report to Thork"] = 29095,
	["Mor'shan Caravan Pick-Up"] = 29109,
	["Mor'shan Caravan Rescue"] = 29110,
	["Demon Seed"] = 29112,
	["Mor'shan Caravan Delivery"] = 29111,
	["After the Crusade"] = 26930,
	["Foxes and Hounds"] = 26931,
	["Foes Before Hoes"] = 26933,
	["Latent Disease"] = 26934,
	["Who Needs Cauldrons?"] = 26978,
	["The Menders' Stead"] = 26952,
	["Warlords of Draenor: The Dark Portal"] = 34398,
	["We're Here to Do One Thing, Maybe Two..."] = 25945,
	["Welcome to the Machine"] = 28096,
	["Trouble at Azurelode"] = 28111,
	["Glorious Harvest"] = 28114,
	["Past Their Prime"] = 28115,
	["Human Infestation"] = 28138,
	["Thieving Little Monsters!"] = 28144,
	["Coastal Delicacies"] = 28146,
	["Muckgill's Flipper or Something..."] = 28154,
	["Deep Mine Rescue"] = 28156,
	["Trouble at the Sludge Fields"] = 28168,
	["No One Here Gets Out Alive"] = 28192,
	["Discretion is Key"] = 28197,
	["For Science!"] = 28199,
	["The Battle for Hillsbrad"] = 28196,
	["Do the Right Thing"] = 28189,
	["Little Girl Lost"] = 28206,
	["Freedom for Lydon"] = 28209,
	["Protocol"] = 28230,
	["Do it for Twinkles"] = 28231,
	["Burnside Must Fall"] = 28235,
	["A Blight Upon the Land"] = 28237,
	["Trouble at Southshore"] = 28251,
	["Studies in Lethality"] = 28324,
	["Green Living"] = 28325,
	["Helcular's Rod Giveth..."] = 28331,
	["Helcular's Command"] = 28332,
	["Angry Scrubbing Bubbles"] = 28329,
	["Trail of Filth"] = 28330,
	["Can You Smell What the Lok'tar is Cooking?"] = 28344,
	["*Gurgle* HELP! *Gurgle*"] = 28345,
	["Stormpike Rendezvous"] = 28348,
	["Preemptive Strike"] = 28356,
	["Kasha Will Fly Again"] = 28354,
	["Terrible Little Creatures"] = 28355,
	["The Road to Purgation"] = 28375,
	["Scourge First... Alliance Later"] = 26921,
	["The Endless Flow"] = 26922,
	["War Machines"] = 26923,
	["Scholomancer"] = 26924,
	["Araj the Summoner"] = 26925,
	["Brute Strength"] = 27117,
	["Victory, For Now"] = 26926,
	["A New Era for the Plaguelands"] = 26999,
	["I Ain't Sayin' You a Gourd-Digger..."] = 26956,
	["Zen'Kiki, the Druid"] = 26953,
	["A Different Approach"] = 26954,
	["Northridge Lumber Mill"] = 26935,
	["Learning the Ropes"] = 27000,
	["Too Close for Comfort"] = 27013,
	["This Means WAR (Wild Arachnid Roundup)"] = 27001,
	["Redpine Thievery"] = 27011,
	["A Gnoll's Resolve"] = 27012,
	["Barrier to Entry"] = 25999,
	["Lessons from the Lost Isles"] = 26003,
	["The Missing Blastgineer"] = 26001,
	["Alliance Attack Plans"] = 26002,
	["Krom'gar Fortress"] = 26004,
	["Ashes to Ashes"] = 26010,
	["Might of the Krom'gar"] = 28084,
	["Seek and Destroy"] = 26009,
	["Dream of a Better Tomorrow"] = 26026,
	["Enemy of the Horde: Marshal Paltrow"] = 26011,
	["BEWARE OF CRAGJAW!"] = 26043,
	["Mr. D's Wild Ride"] = 26028,
	["Orders from Base Camp"] = 26016,
	["Report to Bombgutz"] = 26020,
	["Where Are the Parts?"] = 26044,
	["I Got Your Parts Right Here..."] = 26045,
	["Between a Rock and a Hard Place"] = 26046,
	["And That's Why They Call Them Peons..."] = 26047,
	["Spare Parts Up In Here!"] = 26048,
	["In Defense of Krom'gar Fortress"] = 26058,
	["Eyes and Ears: Malaka'jin"] = 26059,
	["The Queen and Her Court"] = 26063,
	["Da Voodoo: Stormer Heart"] = 26060,
	["Da Voodoo: Ram Horns"] = 26061,
	["Fight On Their Stomachs"] = 26064,
	["Da Voodoo: Resonite Crystal"] = 26062,
	["Jin'Zil's Blessing"] = 26067,
	["Nura Pathfinder"] = 26069,
	["Reinforcements..."] = 26066,
	["Kobold Fury!"] = 26068,
	["All's Quiet on the Southern Front"] = 26073,
	["Beginning of the End"] = 26074,
	["The Turd Problem"] = 26075,
	["Spy Infestation"] = 26076,
	["Final Delivery"] = 26077,
	["To Battlescar!"] = 26082,
	["Proof of Lies"] = 26097,
	["Betrayal at the Grove"] = 26098,
	["Is This Justice?"] = 26099,
	["The General is Dead"] = 26100,
	[""] = ,
},

local quests = {
	[10] = { -- Northern Barrens
	},
	[18] = { -- Tirisfal Glades
	},
	[21] = { -- Silverpine Forest
		["The Warchief Cometh"] = {
			["id"] = 26965,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Warchief's Command: Hillsbrad Foothills!"] = {
			["id"] = 28089,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Guts and Gore"] = {
			["id"] = 26995,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Gilneas Liberation Front"] = {
			["id"] = 26989,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Agony Abounds"] = {
			["id"] = 26992,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Iterating Upon Success"] = {
			["id"] = 26998,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Dangerous Intentions"] = {
			["id"] = 27039,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Waiting to Exsanguinate"] = {
			["id"] = 27045,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Belmont's Report"] = {
			["id"] = 27056,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Warchief's Fleet"] = {
			["id"] = 27065,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Steel Thunder"] = {
			["id"] = 27069,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Give 'em Hell!"] = {
			["id"] = 27073,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Playing Dirty"] = {
			["id"] = 27082,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["It's Only Poisonous if You Ingest It"] = {
			["id"] = 27088,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Lost in the Darkness"] = {
			["id"] = 27093,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Skitterweb Menace"] = {
			["id"] = 27095,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Deeper into Darkness"] = { -- Auto Accepted
			["id"] = 27094,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Orcs are in Order"] = {
			["id"] = 27096,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = {
				shouldTakeFlightPath = true,
				"Forsaken High Command, Silverpine Forest",
			},
		},
		["Rise, Forsaken"] = {
			["id"] = 27097,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["No Escape"] = { -- Auto Accepted
			["id"] = 27099,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Lordaeron"] = {
			["id"] = 27098,
			["reward"] = 0,
			["cancelCinematic"] = true,
			["flightPaths"] = nil,
		},
		["Honor the Dead"] = {
			["id"] = 27180,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Hair of the Dog"] = {
			["id"] = 27226,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Reinforcements from Fenris"] = {
			["id"] = 27231,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Excising the Taint"] = { -- Auto Accepted
			["id"] = 27181,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Seek and Destroy"] = { -- Auto Accepted
			["id"] = 27193,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Cornered and Crushed!"] = { -- Auto Accepted
			["id"] = 27194,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Nowhere to Run"] = {
			["id"] = 27195,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Waters Run Red..."] = {
			["id"] = 27232,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["To Forsaken Forward Command"] = {
			["id"] = 27290,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["In Time, All Will Be Revealed"] = {
			["id"] = 27342,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Losing Ground"] = {
			["id"] = 27333,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The F.C.D."] = {
			["id"] = 27345,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Korok the Colossus"] = { -- Drops from Korok the Colossus, Starts from an Item
			["id"] = 27322,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Break in Communications: Dreadwatch Outpost"] = {
			["id"] = 27349,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Break in Communications: Rutsak's Outpost"] = { -- Auto Accepted
			["id"] = 27350,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Vengeance for Our Soldiers"] = {
			["id"] = 27360,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["On Whose Orders?"] = { -- Auto Accepted
			["id"] = 27364,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["What Tomorrow Brings"] = { -- Auto Accepted
			["id"] = 27401,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Fall Back!"] = {
			["id"] = 27405,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["A Man Named Godfrey"] = {
			["id"] = 27406,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Resistance is Futile"] = { -- Auto Accepted
			["id"] = 27423,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Great Escape"] = {
			["id"] = 27438,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Rise, Godfrey"] = {
			["id"] = 27472,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Breaking the Barrier"] = {
			["id"] = 27474,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Unyielding Servitors"] = {
			["id"] = 27475,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Dalar Dawnweaver"] = {
			["id"] = 27476,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Relios the Relic Keeper"] = {
			["id"] = 27478,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Practical Vengeance"] = {
			["id"] = 27483,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Ley Energies"] = { -- Drops from Arcane Remnants, Starts from an Item
			["id"] = 27480,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Only One May Enter"] = {
			["id"] = 27484,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Transdimensional Warfare: Chapter I"] = {
			["id"] = 27512,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["A Wolf in Bear's Clothing"] = {
			["id"] = 27510,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Transdimensional Warfare: Chapter II"] = {
			["id"] = 27513,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Transdimensional Warfare: Chapter III"] = { -- Auto Accepted
			["id"] = 27518,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Taking the Battlefront"] = {
			["id"] = 27542,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Pyrewood's Fall"] = {
			["id"] = 27550,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Lessons in Fear"] = {
			["id"] = 27548,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Of No Consequence"] = {
			["id"] = 27547,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["I Never Forget a Face"] = { -- Drops from Marsh Crocolisks, Starts from an Item
			["id"] = 27574,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["From the Belly of the Beast"] = {
			["id"] = 27575,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["7th Legion Battle Plans"] = {
			["id"] = 27577,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Sowing Discord"] = {
			["id"] = 27580,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
	},
	[22] = { -- Western Plaguelands
	},
	[25] = { -- Hillsbrad Foothills
	},
	[63] = { -- Ashenvale
	},
	[65] = { -- Stonetalon Mountains
	},
	[70] = { -- Dustwallow Marsh
		["The Black Shield"] = {
			["id"] = 27254,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Suspicious Hoofprints"] = {
			["id"] = 27259,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Lieutenant Paval Reethe"] = {
			["id"] = 27260,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Theramore Spies"] = {
			["id"] = 1201,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Theramore Docks"] = {
			["id"] = 1202,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Hermit of Witch Hill"] = {
			["id"] = 27182,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["A Shambling Threat"] = {
			["id"] = 26682,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Darkmist Extermination"] = {
			["id"] = 25051,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["SMASH BROODQUEEN"] = {
			["id"] = 27229,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Black Shield"] = {
			["id"] = 27255,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Twilight of the Dawn Runner"] = {
			["id"] = 9437,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Lost Report"] = {
			["id"] = 27244,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Marsh Frog Legs"] = {
			["id"] = 27183,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["What's Haunting Witch Hill?"] = {
			["id"] = 27188,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Witch's Bane"] = {
			["id"] = 27189,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Jarl Needs Eyes"] = {
			["id"] = 27184,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Hungry as an Ogre!"] = {
			["id"] = 27191,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Jarl Needs a Blade"] = {
			["id"] = 27186,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
	},
	[85] = { -- Orgrimmar
	},
	[199] = { -- Southern Barrens
		["Clear the High Road"] = {
			["id"] = 24504,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Warriors' Redemption"] = {
			["id"] = 24512,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Feeding the Fear"] = {
			["id"] = 25284,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Holdout at Hunter's Hill"] = {
			["id"] = 24505,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Eye for an Eye"] = {
			["id"] = 24513,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Raptor Scraps"] = {
			["id"] = 24514,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Put the Fear in Them"] = {
			["id"] = 24517,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Low Road"] = { -- Drops from an Honor's Stand Officer, Starts from an Item.
			["id"] = 24518,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Stalling the Survey"] = {
			["id"] = 24519,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Signals in the Sky"] = {
			["id"] = 24515,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Keeping the Dogs at Bay"] = {
			["id"] = 24525,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Bad to Worse"] = {
			["id"] = 24529,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["When Plants Attack"] = {
			["id"] = 24539,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["A Curious Bloom"] = {
			["id"] = 24542,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Speaking Their Language"] = {
			["id"] = 24534,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["A Family Divided"] = {
			["id"] = 24543,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Biological Intervention"] = {
			["id"] = 24565,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Adder Subtraction"] = {
			["id"] = 24570,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Lashvine Seeds"] = {
			["id"] = 24571,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Sowing a Solution"] = {
			["id"] = 24566,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["To Harvest Chaos"] = {
			["id"] = 24574,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Nightmare Scar"] = {
			["id"] = 24601,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Winnoa Pineforest"] = {
			["id"] = 24807,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Lion's Pride"] = {
			["id"] = 24552,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Meet the New Boss"] = {
			["id"] = 24551,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["A Line in the Dirt"] = {
			["id"] = 24546,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Siegebreaker"] = {
			["id"] = 24569,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Honoring the Dead"] = {
			["id"] = 24573,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Taking Back Taurajo"] = {
			["id"] = 24572,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Desolation Hold Inspection"] = {
			["id"] = 24577,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = {
				shouldTakeFlightPath = true,
				"Desolation Hold, Southern Barrens",
			},
		},
		["Changing of the Gar'dul"] = {
			["id"] = 24591,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Parts-is-Parts"] = {
			["id"] = 24619,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Hearts-is-Hearts"] = {
			["id"] = 24620,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Smarts-is-Smarts"] = {
			["id"] = 24621,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Claim the Battle Scar"] = {
			["id"] = 24618,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Silithissues"] = {
			["id"] = 24654,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Firestone Point"] = {
			["id"] = 24667,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Intelligence Warfare"] = {
			["id"] = 24634,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Butcher of Taurajo"] = {
			["id"] = 24637,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Flightmare"] = {
			["id"] = 24631,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Tauren Vengeance"] = {
			["id"] = 24632,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Disturbed Earth"] = {
			["id"] = 24824,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Feeling Thorny"] = {
			["id"] = 26908,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Concern for Mankrik"] = {
			["id"] = 24604,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Mahka's Plea"] = {
			["id"] = 24633,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Don't Stop Bereavin'"] = {
			["id"] = 24603,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Mangletooth"] = {
			["id"] = 24608,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Blood of the Barrens"] = { -- Drops from the Quilboar, Starts from an Item.
			["id"] = 24606,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Echoes of Agamaggan"] = {
			["id"] = 24653,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["A Weezil in the Henhouse"] = {
			["id"] = 24684,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Dwarf Fortress"] = {
			["id"] = 24685,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Sabotage!"] = {
			["id"] = 24747,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Next of Kin"] = {
			["id"] = 25292,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
	},
	[525] = { -- Frostfire Ridge
		["The Home of the Frostwolves"] = {
			["id"] = 33868,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["A Song of Frost and Fire"] = {
			["id"] = 33815,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Of Wolves and Warriors"] = {
			["id"] = 34402,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["For the Horde!"] = {
			["id"] = 34364,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Back to Work"] = {
			["id"] = 34375,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["A Gronnling Problem"] = {
			["id"] = 34592,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Den of Skog"] = {
			["id"] = 34765,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Establish Your Garrison"] = {
			["id"] = 34378,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["What We Need"] = {
			["id"] = 34822,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["What We Got"] = {
			["id"] = 37824,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Build Your Barracks"] = {
			["id"] = 34461,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["We Need An Army"] = {
			["id"] = 34861,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Winds of Change"] = {
			["id"] = 34462,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Mission Probable"] = {
			["id"] = 34775,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
	},
	[572] = { -- Draenor (Cosmic)
		["Azeroth's Last Stand"] = {
			["id"] = 35933,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Onslaught's End"] = {
			["id"] = 34392,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Portal's Power"] = {
			["id"] = 34393,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Cost of War"] = {
			["id"] = 34420,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Blaze of Glory"] = {
			["id"] = 34422,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Bled Dry"] = {
			["id"] = 34421,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Vengeance for the Fallen"] = {
			["id"] = 35241,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Altar Altercation"] = {
			["id"] = 34423,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Kargathar Proving Grounds"] = {
			["id"] = 34425,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["A Potential Ally"] = {
			["id"] = 34427,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Kill Your Hundred"] = {
			["id"] = 34429,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Masters of Shadow"] = {
			["id"] = 34737,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Shadowmoon Clan"] = {
			["id"] = 34739,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Yrel"] = {
			["id"] = 34740,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Keli'dan the Breaker"] = {
			["id"] = 34741,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Prepare for Battle"] = {
			["id"] = 35005,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Battle of the Forge"] = {
			["id"] = 34439,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Ga'nar of the Frostwolf"] = {
			["id"] = 34442,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Gunpowder Plot"] = {
			["id"] = 34987,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Shadow of the Worldbreaker"] = {
			["id"] = 34958,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Polishing the Iron Throne"] = {
			["id"] = 34925,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Prodigal Frostwolf"] = {
			["id"] = 34437,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["Taking a Trip to the Top of the Tank"] = {
			["id"] = 35747,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["A Taste of Iron"] = {
			["id"] = 34445,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
		["The Home Stretch"] = {
			["id"] = 34446,
			["reward"] = 0,
			["cancelCinematic"] = false,
			["flightPaths"] = nil,
		},
	},
};

t.quests = quests;