local addonName, addonTable = ...
local L_DIALOG = addonTable.L_DIALOG
local L_NOTES = addonTable.L_NOTES
local L_GLOBALSTRINGS = addonTable.L_GLOBALSTRINGS

local featuresOptions = {
	name = L_GLOBALSTRINGS["Tabs.Features"],
	handler = HelpMePlay,
	type = "group",
	args = {
		toggleHeader = {
			name = L_GLOBALSTRINGS["Header.Toggles"],
			order = 0,
			type = "header",
		},
		cinematics = {
			name = L_GLOBALSTRINGS["Features.Toggle.Cinematics"],
			order = 1,
			desc = L_GLOBALSTRINGS["Features.Toggle.CinematicsDesc"],
			type = "toggle",
			get = function(info) return HelpMePlayDB.CinematicsEnabled end,
			set = function(info, val) HelpMePlayDB.CinematicsEnabled = val end,
		},
		
		emotes = {
			name = L_GLOBALSTRINGS["Features.Toggle.Emotes"],
			order = 2,
			desc = L_GLOBALSTRINGS["Features.Toggle.EmotesDesc"],
			type = "toggle",
			get = function(info) return HelpMePlayDB.EmotesEnabled end,
			set = function(info, val) HelpMePlayDB.EmotesEnabled = val end,
		},
		flightPaths = {
			name = L_GLOBALSTRINGS["Features.Toggle.FlightPaths"],
			order = 3,
			desc = L_GLOBALSTRINGS["Features.Toggle.FlightPathsDesc"],
			type = "toggle",
			get = function(info) return HelpMePlayDB.FlightPathsEnabled end,
			set = function(info, val) HelpMePlayDB.FlightPathsEnabled = val end,
		},
		gossip = {
			name = L_GLOBALSTRINGS["Features.Toggle.Gossip"],
			order = 4,
			desc = L_GLOBALSTRINGS["Features.Toggle.GossipDesc"],
			type = "toggle",
			get = function(info) return HelpMePlayDB.GossipEnabled end,
			set = function(info, val) HelpMePlayDB.GossipEnabled = val end,
		},
		notes = {
			name = L_GLOBALSTRINGS["Features.Toggle.Notes"],
			order = 5,
			desc = L_GLOBALSTRINGS["Features.Toggle.NotesDesc"],
			type = "toggle",
			get = function(info) return HelpMePlayDB.NotesEnabled end,
			set = function(info, val) HelpMePlayDB.NotesEnabled = val end,
		},
		queues = {
			name = L_GLOBALSTRINGS["Features.Toggle.Queues"],
			order = 6,
			desc = L_GLOBALSTRINGS["Features.Toggle.QueuesDesc"],
			type = "toggle",
			get = function(info) return HelpMePlayDB.QueuesEnabled end,
			set = function(info, val) HelpMePlayDB.QueuesEnabled = val end,
		},
		readyChecks = {
			name = L_GLOBALSTRINGS["Features.Toggle.ReadyChecks"],
			order = 7,
			desc = L_GLOBALSTRINGS["Features.Toggle.ReadyChecksDesc"],
			type = "toggle",
			get = function(info) return HelpMePlayDB.ReadyChecksEnabled end,
			set = function(info, val) HelpMePlayDB.ReadyChecksEnabled = val end,
		},
		repairs = {
			name = L_GLOBALSTRINGS["Features.Toggle.Repairs"],
			order = 8,
			desc = L_GLOBALSTRINGS["Features.Toggle.RepairsDesc"],
			type = "toggle",
			get = function(info) return HelpMePlayDB.RepairsEnabled end,
			set = function(info, val) HelpMePlayDB.RepairsEnabled = val end,
		},
		speech = {
			name = L_GLOBALSTRINGS["Features.Toggle.Speech"],
			order = 9,
			desc = L_GLOBALSTRINGS["Features.Toggle.SpeechDesc"],
			type = "toggle",
			get = function(info) return HelpMePlayDB.SpeechEnabled end,
			set = function(info, val) HelpMePlayDB.SpeechEnabled = val end,
		},
		trainers = {
			name = L_GLOBALSTRINGS["Features.Toggle.Trainers"],
			order = 10,
			desc = L_GLOBALSTRINGS["Features.Toggle.TrainersDesc"],
			type = "toggle",
			get = function(info) return HelpMePlayDB.TrainersEnabled end,
			set = function(info, val) HelpMePlayDB.TrainersEnabled = val end,
		},
		vehicles = {
			name = L_GLOBALSTRINGS["Features.Toggle.Vehicles"],
			order = 11,
			desc = L_GLOBALSTRINGS["Features.Toggle.VehiclesDesc"],
			type = "toggle",
			get = function(info) return HelpMePlayDB.VehiclesEnabled end,
			set = function(info, val) HelpMePlayDB.VehiclesEnabled = val end,
		},
		warMode = {
			name = L_GLOBALSTRINGS["Features.Toggle.WarMode"],
			order = 12,
			desc = L_GLOBALSTRINGS["Features.Toggle.WarModeDesc"],
			type = "toggle",
			get = function(info) return HelpMePlayDB.WarModeEnabled end,
			set = function(info, val) HelpMePlayDB.WarModeEnabled = val end,
		},
		waypoints = {
			name = L_GLOBALSTRINGS["Features.Toggle.Waypoints"],
			order = 13,
			desc = L_GLOBALSTRINGS["Features.Toggle.WaypointsDesc"],
			type = "toggle",
			get = function(info) return HelpMePlayDB.WaypointsEnabled end,
			set = function(info, val) HelpMePlayDB.WaypointsEnabled = val end,
		},
		extrasHeader = {
			name = L_GLOBALSTRINGS["Header.Extras"],
			order = 20,
			type = "header",
		},
		holidayQueues = {
			name = L_GLOBALSTRINGS["Features.Toggle.Extras.HolidayQueues"],
			order = 21,
			desc = L_GLOBALSTRINGS["Features.Toggle.Extras.HolidayQueuesDesc"],
			type = "toggle",
			get = function(info) return HelpMePlayDB.HolidayQueuesEnabled end,
			set = function(info, val) HelpMePlayDB.HolidayQueuesEnabled = val end,
		},
		hideNPE = {
			name = L_GLOBALSTRINGS["Features.Toggle.Extras.HideNPE"],
			order = 22,
			desc = L_GLOBALSTRINGS["Features.Toggle.Extras.HideNPEDesc"],
			type = "toggle",
			get = function(info) return HelpMePlayDB.HideNPE end,
			set = function(info, val) HelpMePlayDB.HideNPE = val end,
		},
	},
}
addonTable.featuresOptions = featuresOptions